version: '3.4'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  app:
    build:
      context: .
      target: production # refers to step in Dockerfile (multi-stage build)
    ports:
      - 8080:8080
    image: app
    container_name: app
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
  test:
    build:
      context: .
      target: test
    depends_on:
      - mongo
      - app
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
    command: npm test
    volumes:
      - ./:/app
