version: "3"

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
