version: '3'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  app:
    build: .
    ports:
      - 8080:8080
    image: app
    container_name: app
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
