version: '3'

services:
  app-tests:
    image: app
    command: 'npm test'
    environment:
      NODE_ENV: 'TEST'
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
    depends_on:
      - mongo
      - app
